GET http://localhost:3001/api/persons

### Single person
GET http://localhost:3001/api/persons/67c0d8925425cfb40e14bd82

###
DELETE http://localhost:3001/api/persons/67c0d73840876b394fe725bc

### Good request
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Animaniacs",
  "number": "555-292-546"
}

### Bad request
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "11111"
}

###
GET http://localhost:3001/info

###
PUT http://localhost:3001/api/persons/67ccb2734bcf1793cb9bbd9b
Content-Type: application/json

{
  "name": "Gonzalez",
  "number": "111-192-516"
}
