GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/1

### Good request
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Inspector Gadget",
  "number": "555-292-546"
}

### Bad request
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "11111"
}

