GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Lucky Luke",
  "number": "999-222-555"
}

### Bad request
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "11111"
}

